#!/bin/bash
#
# tomcat7      This shell script takes care of starting and stopping Tomcat
#
# chkconfig: 234 80 20
#
### BEGIN INIT INFO
# Provides: tomcat7
# Required-Start: $network $syslog
# Required-Stop: $network $syslog
# Default-Start:
# Default-Stop:
# Description: Release implementation for Servlet 2.5 and JSP 2.1
# Short-Description: start and stop tomcat
### END INIT INFO
#
#

CATALINA_HOME=/opt/tomcat7

function start() 
{
	sh $CATALINA_HOME/bin/startup.sh
}
function stop() 
{
	sh $CATALINA_HOME/bin/shutdown.sh
}
case $1 in
start)
	start
	;;
stop)
	stop
	;;
restart)
	stop
	start
	;;

esac
exit 0
